# Generated by Django 5.2.14 on 2026-05-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0003_userprofile_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="medications/photos/",
                verbose_name="Фотография",
            ),
        ),
    ]
